version: 0.2

phases:
  install:
    runtime-versions:
      php: 7.3
  build:
    commands:
      - cd /usr/local/bin && ls -R
      - cd /usr/local/lib/php/extensions/no-debug-non-zts-20180731 && ls -R
      - cd $CODEBUILD_SRC_DIR
      - php --version
      - python --version
      - python3 --version
      - php test.php
      - python test.py