version: 0.2

phases:
  install:
    runtime-versions:
      php: 7.3
  build:
    commands:
      - cd /usr/local/bin && ls -R
      - php --version
      - python --version
      - python3 --version
      - php test.php
      - python test.py